---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-deployment-loadbalancer
  labels:
    app: spring-boot-k8s-loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s-loadbalancer
  template:
    metadata:
      labels:
        app: spring-boot-k8s-loadbalancer
    spec:
      containers:
        - name: spring-boot-k8s-loadbalancer
          image: collins6299/job-application-tracker:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: myapp-app-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080